package mail;

import model.AutoReplyConfig;

import javax.mail.*;
import javax.mail.internet.*;
import javax.mail.search.FlagTerm;
import java.util.*;
import java.util.concurrent.*;

public class AutoReplyService {

    private static final String SYSTEM_EMAIL = "mangoisme03@gmail.com";
    private static final String SYSTEM_PASSWORD = "ecejffzypkzvymwn";

    private ScheduledExecutorService scheduler;
    private AutoReplyConfig config;

    // chống reply trùng
    private final Set<String> repliedKeys = new HashSet<>();

    public void start(AutoReplyConfig config) {
        this.config = config;

        scheduler = Executors.newSingleThreadScheduledExecutor();
        scheduler.scheduleAtFixedRate(
                this::checkAndReply, 0, 30, TimeUnit.SECONDS
        );

        System.out.println("Auto Reply Service started.");
    }

    public void stop() {
        if (scheduler != null) {
            scheduler.shutdownNow();
            System.out.println("Auto Reply Service stopped.");
        }
    }

    public void updateConfig(AutoReplyConfig config) {
        this.config = config;
    }

    private void checkAndReply() {

        if (config == null || !config.isEnabled()) {
            System.out.println("Auto reply disabled.");
            return;
        }

        System.out.println("Checking inbox...");

        try {
            // ================= IMAP =================
            Properties props = new Properties();
            props.put("mail.imap.host", "imap.gmail.com");
            props.put("mail.imap.port", "993");
            props.put("mail.imap.ssl.enable", "true");
            props.put("mail.imap.ssl.trust", "*");

            Session session = Session.getInstance(props, new Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(SYSTEM_EMAIL, SYSTEM_PASSWORD);
                }
            });

            Store store = session.getStore("imap");
            store.connect();

            Folder inbox = store.getFolder("INBOX");
            inbox.open(Folder.READ_WRITE);

            Message[] messages = inbox.search(
                    new FlagTerm(new Flags(Flags.Flag.SEEN), false)
            );

            System.out.println("Unseen emails: " + messages.length);

            for (Message msg : messages) {

                try {
                    String from = InternetAddress.toString(msg.getFrom());
                    String fromEmail = extractEmail(from);
                    String subject = msg.getSubject();

                    String key = fromEmail + "|" + subject;

                    // ❌ tránh reply trùng
                    if (repliedKeys.contains(key)) continue;

                    System.out.println("From: " + fromEmail);

                    // ❌ tránh self
                    if (fromEmail.equalsIgnoreCase(SYSTEM_EMAIL)) continue;

                    // ❌ mail hệ thống
                    if (isSystemMail(fromEmail)) {
                        System.out.println("Skip system mail");
                        msg.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }

                    // ❌ mail auto
                    if (isAutoGenerated(msg)) {
                        System.out.println("Skip auto mail");
                        msg.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }

                    // ❌ marketing
                    if (isMarketingMail(subject)) {
                        System.out.println("Skip marketing mail");
                        msg.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }

                    // ❌ loop
                    if (subject != null && subject.toLowerCase().startsWith("re:")) {
                        System.out.println("Skip reply loop");
                        msg.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }

                    // ❌ chỉ reply người thật (tuỳ chọn mạnh)
                    if (!fromEmail.endsWith("@gmail.com")) {
                        System.out.println("Skip non-human mail");
                        msg.setFlag(Flags.Flag.SEEN, true);
                        continue;
                    }

                    // ================= SEND =================
                    sendReply(msg, config.getReplyTemplate());

                    System.out.println("Replied to: " + fromEmail);

                    repliedKeys.add(key);
                    msg.setFlag(Flags.Flag.SEEN, true);

                    Thread.sleep(2000);

                } catch (Exception e) {
                    System.out.println("Error mail: " + e.getMessage());
                }
            }

            inbox.close(false);
            store.close();

        } catch (Exception e) {
            System.out.println("Auto reply error: " + e.getMessage());
        }
    }

    // ================= FILTER =================

    private boolean isSystemMail(String email) {
        if (email == null) return true;

        email = email.toLowerCase();

        return email.contains("no-reply")
                || email.contains("noreply")
                || email.contains("no_reply")
                || email.contains("donotreply")
                || email.contains("mailer-daemon")
                || email.contains("postmaster")
                || email.contains("notification")
                || email.contains("support")
                || email.contains("admin")
                || email.contains("service")
                || email.contains("account")
                || email.contains("security")
                || email.contains("newsletter")
                || email.contains("marketing")
                || email.contains("team@")
                || email.contains("mail@");
    }

    private boolean isAutoGenerated(Message msg) {
        try {
            String[] auto = msg.getHeader("Auto-Submitted");
            if (auto != null && !auto[0].equalsIgnoreCase("no")) return true;

            String[] precedence = msg.getHeader("Precedence");
            if (precedence != null && (
                    precedence[0].equalsIgnoreCase("bulk") ||
                            precedence[0].equalsIgnoreCase("list") ||
                            precedence[0].equalsIgnoreCase("junk"))) {
                return true;
            }

            String[] suppress = msg.getHeader("X-Auto-Response-Suppress");
            if (suppress != null) return true;

        } catch (Exception ignored) {}

        return false;
    }

    private boolean isMarketingMail(String subject) {
        if (subject == null) return false;

        subject = subject.toLowerCase();

        return subject.contains("sale")
                || subject.contains("discount")
                || subject.contains("offer")
                || subject.contains("promotion")
                || subject.contains("newsletter")
                || subject.contains("unsubscribe")
                || subject.contains("%");
    }

    // ================= HELPER =================

    private String extractEmail(String from) {
        try {
            InternetAddress[] addrs = InternetAddress.parse(from);
            if (addrs.length > 0) {
                return addrs[0].getAddress().trim().toLowerCase();
            }
        } catch (Exception ignored) {}
        return from.trim().toLowerCase();
    }

    private void sendReply(Message original, String template) throws Exception {

        Properties props = new Properties();

        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        // 🔥 FIX SSL
        props.put("mail.smtp.ssl.trust", "*");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.starttls.required", "true");

        Session session = Session.getInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(SYSTEM_EMAIL, SYSTEM_PASSWORD);
            }
        });

        Message reply = new MimeMessage(session);
        reply.setRecipients(Message.RecipientType.TO, original.getFrom());

        String subject = original.getSubject();
        if (subject == null) subject = "";
        if (!subject.startsWith("Re:")) subject = "Re: " + subject;

        reply.setSubject(subject);
        reply.setFrom(new InternetAddress(SYSTEM_EMAIL));

        String messageId = ((MimeMessage) original).getMessageID();
        if (messageId != null) {
            reply.setHeader("In-Reply-To", messageId);
            reply.setHeader("References", messageId);
        }

        reply.setContent(template, "text/html; charset=utf-8");

        Transport.send(reply);
    }
}